# Generated by Django 4.0.4 on 2022-05-05 08:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post_image',
            fields=[
                ('username', models.CharField(max_length=150)),
                ('postid', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('photo', models.ImageField(height_field='480', upload_to='posted_images/', width_field='480')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 5, 5, 8, 47, 14, 439275, tzinfo=utc))),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
