# Generated by Django 4.0.4 on 2022-05-05 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codebook_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_image',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 8, 53, 28, 584285, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post_image',
            name='photo',
            field=models.ImageField(upload_to='posted_images/'),
        ),
    ]
