# Generated by Django 4.0.4 on 2022-05-05 12:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codebook_posts', '0003_post_text_post_videos_post_image_catagory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('username', models.CharField(max_length=150)),
                ('postid', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='posted_images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='posted_videos/')),
                ('description', models.TextField(max_length=1500)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 5, 5, 12, 11, 34, 218339, tzinfo=utc))),
                ('catagory', models.CharField(default='image', max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='post_image',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 12, 11, 34, 217027, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post_text',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 12, 11, 34, 217962, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post_videos',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 12, 11, 34, 217605, tzinfo=utc)),
        ),
    ]
