# Generated by Django 4.0.4 on 2022-05-10 06:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codebook_posts', '0010_alter_post_image_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_image',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 6, 10, 2, 998934, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post_text',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 6, 10, 2, 999887, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post_videos',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 6, 10, 2, 999508, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 6, 10, 3, 421, tzinfo=utc)),
        ),
    ]
