# Generated by Django 4.0.4 on 2022-05-10 10:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codebook_posts', '0012_alter_post_image_created_at_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post_image',
        ),
        migrations.DeleteModel(
            name='post_text',
        ),
        migrations.DeleteModel(
            name='post_videos',
        ),
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 10, 10, 1, 2, 603384, tzinfo=utc)),
        ),
    ]
