# Generated by Django 4.0.4 on 2022-05-13 13:02

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('codebook_posts', '0032_alter_posts_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 13, 13, 2, 11, 185805, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_username', models.CharField(max_length=150)),
                ('postid_toshow', models.BigIntegerField(blank=True, null=True)),
                ('friend_username', models.CharField(max_length=150)),
                ('operation', models.CharField(max_length=25)),
                ('postid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codebook_posts.posts')),
            ],
        ),
    ]
