# Generated by Django 4.0.4 on 2022-05-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebook_user', '0004_user_about_alter_user_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='friends2',
            fields=[
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('friend_with', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('temp', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
