# Generated by Django 4.0.4 on 2022-05-10 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebook_user', '0005_friends2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends2',
            name='temp',
            field=models.AutoField(max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
