# Generated by Django 4.0.4 on 2022-05-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebook_user', '0007_user_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_model',
            name='about',
            field=models.CharField(blank=True, default='its my about section', max_length=500),
        ),
    ]
