# Generated by Django 4.0.4 on 2022-05-12 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codebook_posts', '0032_alter_posts_created_at'),
        ('codebook_user', '0011_liked_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_commnets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('comment', models.CharField(max_length=250)),
                ('postid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codebook_posts.posts')),
            ],
        ),
    ]
